---
- name: Install hadoop master node
  hosts: hadoop-master
  gather_facts: false
  become: yes
  remote_user: ubuntu

  roles:
    - preinstall
    - common
    - oraclejava8

- name: Install hadoop data node
  hosts: hadoop-data
  gather_facts: false
  become: yes
  remote_user: ubuntu

  roles:
    - common
    - oraclejava8